#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: jonimofo
  description: Installs and configures Fail2Ban to protect services from brute-force attacks on Debian-based systems.
  license: GPL-2.0-or-later
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - security
    - firewall
    - system
    - fail2ban
    - hardening
dependencies: []
