#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: jonimofo
  description: Installs Neovim and configures AstroNvim for specified users.
  license: GPL-2.0-or-later
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - nvim
    - astronvim
    - neovim
    - editor
    - development
dependencies: []
