#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: jonimofo
  description: Hardens SSH server configuration and manages user access with authorized keys on Debian-based systems.
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - security
    - system
    - ssh
    - users
    - hardening
dependencies: []
