#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: jonimofo
  description: Installs lazydocker, a terminal UI for Docker and Docker Compose.
  license: GPL-2.0-or-later
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - docker
    - tools
    - utility
    - cli
    - terminal
    - development
dependencies: []
